# Generated by Django 5.2.17 on 2026-09-29 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('avatar_emoji', models.CharField(default='🗣️', max_length=8)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('last_practice_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Twister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('text', models.TextField()),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Insane')], db_index=True, default=1)),
                ('origin', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern')], db_index=True, default='classic', max_length=10)),
                ('tip', models.CharField(blank=True, help_text='Coaching hint shown before practice', max_length=240)),
                ('focus_sounds', models.JSONField(blank=True, default=list, help_text='e.g. ["s", "sh"]')),
                ('word_count', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twisters', to='twisters.category')),
            ],
            options={
                'ordering': ['difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='twisters.profile')),
                ('twister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='twisters.twister')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'twister'), name='uniq_favorite')],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(blank=True)),
                ('accuracy', models.FloatField(help_text='0..1, server-computed')),
                ('duration_ms', models.PositiveIntegerField()),
                ('wpm', models.FloatField()),
                ('score', models.PositiveSmallIntegerField(db_index=True)),
                ('xp_awarded', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='twisters.profile')),
                ('twister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='twisters.twister')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['twister', '-score'], name='twisters_at_twister_702735_idx'), models.Index(fields=['profile', '-created_at'], name='twisters_at_profile_b4164e_idx')],
            },
        ),
    ]
