# Generated by Django 5.2.17 on 2026-09-30 07:28

import django.core.validators
import django.db.models.deletion
import twisters.models
import uuid
from django.db import migrations, models


# Decision D1 (docs/features/11-decisions-log.md). Frozen here on purpose: migrations must not import live constants.
FREE_PLAN_LIMITS = {
    "recordings_max": 5,
    "recording_ms_max": 180_000,
    "storage_bytes_max": 104_857_600,
    "retention_days": 30,
    "share_max_days": 7,
}


def seed_free_plan(apps, schema_editor):
    apps.get_model("twisters", "Plan").objects.update_or_create(
        code="free", defaults={"name": "Free", "limits": FREE_PLAN_LIMITS})


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('code', models.SlugField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(seed_free_plan, migrations.RunPython.noop),
        migrations.RenameField(model_name='profile', old_name='last_practice_date', new_name='last_activity_date'),
        migrations.AddField(
            model_name='profile',
            name='guest_migrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateField(blank=True, help_text='Local date of the last streak-qualifying activity', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', help_text="IANA name; decides what 'today' means", max_length=64, validators=[twisters.models.validate_timezone]),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.ForeignKey(db_column='plan_code', default='free', on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='twisters.plan'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to='twisters.profile')),
                ('default_mode', models.CharField(choices=[('read_along', 'Read along'), ('speak_score', 'Speak & score'), ('record', 'Record')], default='speak_score', max_length=12)),
                ('display_style', models.CharField(choices=[('word', 'Word by word'), ('line', 'Line by line'), ('scroll', 'Continuous scroll')], default='word', max_length=6)),
                ('accent_lang', models.CharField(choices=[('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('en-IN', 'English (India)'), ('en-AU', 'English (Australia)')], default='en-US', max_length=5)),
                ('wpm', models.PositiveSmallIntegerField(default=110, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)])),
                ('threshold_pct', models.PositiveSmallIntegerField(default=35, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(60)])),
                ('font_scale', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.8), django.core.validators.MaxValueValidator(2.0)])),
                ('loop_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('countdown_s', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('mirror_text', models.BooleanField(default=False)),
                ('punctuation_pauses', models.BooleanField(default=True)),
                ('metronome', models.BooleanField(default=False)),
                ('listen_first', models.BooleanField(default=False)),
                ('tts_voice', models.CharField(blank=True, help_text='Device-specific voiceURI; empty = default', max_length=200)),
                ('tts_rate', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1.5)])),
                ('reduce_motion', models.BooleanField(default=False)),
                ('dyslexia_font', models.BooleanField(default=False)),
                ('high_contrast', models.BooleanField(default=False)),
                ('save_voice_default', models.BooleanField(default=False)),
                ('record_layout', models.SlugField(default='camera_text', max_length=24)),
                ('record_resolution', models.CharField(choices=[('720p', '720p'), ('1080p', '1080p')], default='720p', max_length=5)),
                ('speed_ladder', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('wpm__gte', 40), ('wpm__lte', 300)), name='pref_wpm_range'), models.CheckConstraint(condition=models.Q(('threshold_pct__gte', 20), ('threshold_pct__lte', 60)), name='pref_threshold_pct_range'), models.CheckConstraint(condition=models.Q(('font_scale__gte', 0.8), ('font_scale__lte', 2.0)), name='pref_font_scale_range'), models.CheckConstraint(condition=models.Q(('loop_count__gte', 0), ('loop_count__lte', 10)), name='pref_loop_count_range'), models.CheckConstraint(condition=models.Q(('countdown_s__gte', 0), ('countdown_s__lte', 5)), name='pref_countdown_s_range'), models.CheckConstraint(condition=models.Q(('tts_rate__gte', 0.5), ('tts_rate__lte', 1.5)), name='pref_tts_rate_range')],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_date', models.DateField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('active_ms', models.PositiveIntegerField(default=0)),
                ('read_along_ms', models.PositiveIntegerField(default=0)),
                ('read_along_passes', models.PositiveSmallIntegerField(default=0)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('read_along_xp', models.PositiveIntegerField(default=0)),
                ('qualifies_streak', models.BooleanField(default=False)),
                ('freeze_used', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to='twisters.profile')),
            ],
            options={
                'verbose_name_plural': 'daily activity',
                'constraints': [models.UniqueConstraint(fields=('profile', 'local_date'), name='uniq_daily_activity')],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_session_id', models.CharField(help_text='Client-generated id; makes create idempotent', max_length=64)),
                ('mode', models.CharField(choices=[('read_along', 'Read along'), ('speak_score', 'Speak & score'), ('record', 'Record')], max_length=12)),
                ('submode', models.CharField(blank=True, choices=[('test', 'Test'), ('train', 'Train'), ('drill', 'Drill')], max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=10)),
                ('ended_reason', models.CharField(blank=True, choices=[('user', 'User'), ('finished', 'Finished'), ('tab_hidden', 'Tab hidden'), ('timeout', 'Timeout'), ('error', 'Error')], max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_ms', models.PositiveIntegerField(default=0)),
                ('loops_completed', models.PositiveSmallIntegerField(default=0)),
                ('passes_completed', models.PositiveSmallIntegerField(default=0, help_text='Full passes through the text')),
                ('avg_wpm', models.FloatField(blank=True, null=True)),
                ('settings_snapshot', models.JSONField(blank=True, default=dict)),
                ('engine', models.CharField(blank=True, choices=[('text_layer', 'Text layer'), ('ondevice', 'On-device'), ('worker', 'Worker'), ('none', 'None')], max_length=12)),
                ('user_agent_family', models.CharField(blank=True, max_length=40)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='twisters.profile')),
                ('twister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='twisters.twister')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['profile', '-started_at'], name='twisters_pr_profile_5f401b_idx'), models.Index(fields=['twister', 'mode'], name='twisters_pr_twister_311c8f_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'client_session_id'), name='uniq_session_client_id')],
            },
        ),
    ]
