# Generated by Django 5.2.17 on 2026-09-30 07:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


# Flags named in docs/features/09-implementation-plan.md §2. Shipped features start on; unbuilt ones start off
# (flip in the admin, or kill a live one by unticking `enabled`).
SHIPPED = {"practice_hub": "Practice Hub shell", "read_along": "Read-along mode"}
PLANNED = {
    "speak_v2": "Speak & score v2", "accurate_mode": "On-device accurate engine", "spot_checks": "Worker spot-checks",
    "record_local": "Local recording", "record_screen": "Screen recording", "record_region": "Region capture",
    "record_cloud": "Cloud recordings", "share_links": "Share links", "achievements": "Achievements",
    "generate_twister": "AI twister generation", "reminders": "Reminders", "weekly_boards": "Weekly leaderboards",
}


def seed_flags(apps, schema_editor):
    Flag = apps.get_model("twisters", "FeatureFlag")
    for code, description in {**SHIPPED, **PLANNED}.items():
        Flag.objects.update_or_create(code=code, defaults={"description": description, "enabled": code in SHIPPED})


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0002_practice_hub_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=False)),
                ('rollout_pct', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)])),
                ('allow_list', models.JSONField(blank=True, default=list, help_text='Profile ids that always get the flag')),
            ],
        ),
        migrations.CreateModel(
            name='SyncBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_batch_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('guest_signup', 'Guest sign-up'), ('offline_queue', 'Offline queue')], default='guest_signup', max_length=14)),
                ('payload_sha256', models.CharField(blank=True, max_length=64)),
                ('attempts_imported', models.PositiveIntegerField(default=0)),
                ('favorites_imported', models.PositiveIntegerField(default=0)),
                ('rejected', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='client_attempt_id',
            field=models.UUIDField(blank=True, help_text='Client-generated; makes imports idempotent', null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='wpm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Null = automatic, by twister difficulty (90/110/130/150)', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('profile', 'client_attempt_id'), name='uniq_attempt_client_id'),
        ),
        migrations.AddConstraint(
            model_name='featureflag',
            constraint=models.CheckConstraint(condition=models.Q(('rollout_pct__lte', 100)), name='flag_rollout_pct_range'),
        ),
        migrations.AddField(
            model_name='syncbatch',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_batches', to='twisters.profile'),
        ),
        migrations.AddConstraint(
            model_name='syncbatch',
            constraint=models.UniqueConstraint(fields=('profile', 'client_batch_id'), name='uniq_sync_batch'),
        ),
        migrations.RunPython(seed_flags, migrations.RunPython.noop),
    ]
