# Generated by Django 5.2.17 on 2026-09-30 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_public_ids(apps, schema_editor):
    Attempt = apps.get_model('twisters', 'Attempt')
    for attempt in Attempt.objects.filter(public_id__isnull=True).only('pk').iterator():
        Attempt.objects.filter(pk=attempt.pk).update(public_id=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0004_metronome_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcousticModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. w2v-espeak-lv60-int8-r1', max_length=80)),
                ('base_model', models.CharField(max_length=120)),
                ('licence', models.CharField(max_length=60)),
                ('quantization', models.CharField(choices=[('fp32', 'fp32'), ('fp16', 'fp16'), ('int8', 'int8')], max_length=4)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('download_url', models.URLField(blank=True, help_text='Our own storage, never a third-party host')),
                ('label_map_version', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-released_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TwisterPronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Normalised (see speak.normalise)', max_length=64)),
                ('arpabet', models.CharField(blank=True, help_text="Space-separated phones; alternative pronunciations are separated by ' | '", max_length=200)),
                ('ipa', models.CharField(blank=True, max_length=200)),
                ('respelling', models.CharField(blank=True, help_text='e.g. PEK-uhld', max_length=80)),
                ('accepted_variants', models.JSONField(blank=True, default=list, help_text='Spoken forms counted correct')),
                ('accent', models.CharField(blank=True, choices=[('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('en-IN', 'English (India)'), ('en-AU', 'English (Australia)')], help_text='Blank = every accent', max_length=5)),
                ('source', models.CharField(choices=[('cmudict', 'CMUdict'), ('rule', 'Rule'), ('override', 'Override'), ('g2p', 'G2P')], default='override', max_length=8)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhonemeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneme_pair', models.CharField(max_length=20)),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTwisterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('test_attempts_count', models.PositiveIntegerField(default=0)),
                ('best_score', models.PositiveSmallIntegerField(blank=True, help_text='Verified test', null=True)),
                ('best_practice_score', models.PositiveSmallIntegerField(blank=True, help_text='Provisional test', null=True)),
                ('best_test_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('mastery_days_hit', models.PositiveSmallIntegerField(default=0)),
                ('mastery_last_day', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'user twister stats',
            },
        ),
        migrations.CreateModel(
            name='UserWordStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_norm', models.CharField(max_length=64)),
                ('seen', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('near', models.PositiveIntegerField(default=0)),
                ('wrong', models.PositiveIntegerField(default=0)),
                ('missed', models.PositiveIntegerField(default=0)),
                ('recent_error_rate', models.FloatField(default=0.0, help_text='EMA of per-attempt error (0..1)')),
                ('weakness', models.FloatField(default=0.0, help_text='0..1, recency-weighted')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('streak_correct', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='audio_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Aggregate for train/drill (no AttemptWord rows)'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='completeness',
            field=models.FloatField(blank=True, help_text='Share of expected words found', null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='engine',
            field=models.CharField(choices=[('text_layer', 'Text layer'), ('ondevice', 'On-device'), ('worker', 'Worker'), ('none', 'None')], default='text_layer', max_length=12),
        ),
        migrations.AddField(
            model_name='attempt',
            name='engine_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='engine_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='attempt',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='fluency_score',
            field=models.FloatField(blank=True, help_text='0..1 (v2)', null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='gop_score',
            field=models.FloatField(blank=True, help_text='Acoustic score from our engine, 0..100', null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_personal_best',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='kind',
            field=models.CharField(choices=[('test', 'Test'), ('train', 'Train'), ('drill', 'Drill'), ('record', 'Record')], db_index=True, default='test', max_length=6),
        ),
        migrations.AddField(
            model_name='attempt',
            name='lang',
            field=models.CharField(blank=True, choices=[('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('en-IN', 'English (India)'), ('en-AU', 'English (Australia)')], max_length=5),
        ),
        migrations.AddField(
            model_name='attempt',
            name='long_pause_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='nonce',
            field=models.UUIDField(blank=True, help_text='Per-attempt anti-replay token', null=True),
        ),
        # public_id: add nullable -> give every existing row its own uuid -> enforce unique/non-null.
        migrations.AddField(
            model_name='attempt',
            name='public_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(backfill_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attempt',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='For score-card sharing', unique=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='quality',
            field=models.JSONField(blank=True, default=dict, help_text='snr, clipping, blank_ratio'),
        ),
        # Rows that exist now were scored by the v1 formula (70 accuracy / 30 speed); new rows default to v2.
        migrations.AddField(
            model_name='attempt',
            name='score_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score_version',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='attempt',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='twisters.practicesession'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='speed_score',
            field=models.FloatField(blank=True, help_text='0..1 (v2)', null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='spot_check_delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='spot_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='verification_status',
            field=models.CharField(choices=[('none', 'None'), ('device', 'Device'), ('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='none', max_length=8),
        ),
        migrations.AddField(
            model_name='attempt',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='voice_asset_id',
            field=models.UUIDField(blank=True, help_text='MediaAsset (ERD 06c); a plain id until that table ships', null=True),
        ),
        migrations.AddField(
            model_name='twister',
            name='phoneme_version',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='twister',
            name='phonemes',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='word -> [ARPAbet variants], built offline by `build_pronunciations`'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='client_attempt_id',
            field=models.UUIDField(blank=True, help_text='Client-generated; makes submissions idempotent', null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='model_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='twisters.acousticmodelversion'),
        ),
        migrations.CreateModel(
            name='AttemptWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('spoken_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_word', models.CharField(blank=True, max_length=64)),
                ('spoken_word', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('correct', 'Correct'), ('near', 'Near'), ('wrong', 'Wrong'), ('missed', 'Missed'), ('extra', 'Extra')], max_length=8)),
                ('reason', models.CharField(blank=True, choices=[('homophone', 'Homophone'), ('focus_swap', 'Focus sound swapped'), ('slurred', 'Slurred'), ('uncertain', 'Uncertain'), ('low_conf', 'Low confidence')], max_length=12)),
                ('credit', models.FloatField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('acoustic_score', models.FloatField(blank=True, help_text='0..100 from GOP features', null=True)),
                ('phoneme_distance', models.FloatField(blank=True, null=True)),
                ('start_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='twisters.attempt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AttemptPhoneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveSmallIntegerField()),
                ('target_phoneme', models.CharField(max_length=8)),
                ('heard_phoneme', models.CharField(blank=True, help_text='Empty if deleted', max_length=8)),
                ('variant_used', models.CharField(blank=True, max_length=40)),
                ('verdict', models.CharField(choices=[('ok', 'OK'), ('weak', 'Weak'), ('substituted', 'Substituted'), ('deleted', 'Deleted'), ('uncertain', 'Uncertain')], max_length=12)),
                ('delta', models.FloatField(blank=True, help_text='Substitution test, log-likelihood ratio', null=True)),
                ('lpp', models.FloatField(blank=True, help_text='Mean log posterior of target', null=True)),
                ('lpr', models.FloatField(blank=True, help_text='Log posterior ratio vs best competitor', null=True)),
                ('start_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonemes', to='twisters.attemptword')),
            ],
            options={
                'ordering': ['attempt_word_id', 'idx'],
            },
        ),
        migrations.CreateModel(
            name='AttemptFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judged_correct', models.BooleanField(help_text='User says the verdict was right')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('donated_audio', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_feedback', to='twisters.profile')),
                ('attempt_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='twisters.attemptword')),
            ],
            options={
                'verbose_name_plural': 'attempt feedback',
            },
        ),
        migrations.CreateModel(
            name='ScoringJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_asset_id', models.UUIDField(blank=True, help_text='MediaAsset (ERD 06c); a plain id until that table ships', null=True)),
                ('kind', models.CharField(choices=[('spot_check', 'Spot check'), ('verify', 'Verify'), ('device_unsupported', 'Device unsupported')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('expired', 'Expired')], default='queued', max_length=8)),
                ('tries', models.PositiveSmallIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_jobs', to='twisters.attempt')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='twisters.acousticmodelversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. sp-2026-10-a', max_length=40, unique=True)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('accent_packs', models.JSONField(blank=True, default=dict)),
                ('confusion_map', models.JSONField(blank=True, default=dict)),
                ('calibration_set', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scoring_profiles', to='twisters.acousticmodelversion')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='scoring_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='twisters.scoringprofile'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['profile', 'twister', '-created_at'], name='attempt_hist_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(condition=models.Q(('flagged', False), ('kind', 'test'), ('verification_status', 'verified')), fields=['twister', '-score'], name='attempt_board_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(condition=models.Q(('verification_status', 'pending')), fields=['verification_status', 'created_at'], name='attempt_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('nonce__isnull', False)), fields=('profile', 'nonce'), name='uniq_attempt_nonce'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('audio_sha256__isnull', False)), fields=('audio_sha256',), name='uniq_attempt_audio_hash'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(('score__lte', 100)), name='attempt_score_range'),
        ),
        migrations.AddField(
            model_name='twisterpronunciation',
            name='twister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='twisters.twister'),
        ),
        migrations.AddField(
            model_name='userphonemestat',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_stats', to='twisters.profile'),
        ),
        migrations.AddField(
            model_name='usertwisterstats',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twister_stats', to='twisters.profile'),
        ),
        migrations.AddField(
            model_name='usertwisterstats',
            name='twister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='twisters.twister'),
        ),
        migrations.AddField(
            model_name='userwordstat',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_stats', to='twisters.profile'),
        ),
        migrations.AddIndex(
            model_name='attemptword',
            index=models.Index(fields=['attempt'], name='twisters_at_attempt_1485b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptword',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['correct', 'near', 'wrong', 'missed', 'extra'])), name='attemptword_status'),
        ),
        migrations.AddIndex(
            model_name='attemptphoneme',
            index=models.Index(fields=['attempt_word'], name='twisters_at_attempt_81e88e_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptphoneme',
            index=models.Index(condition=models.Q(('verdict', 'substituted')), fields=['target_phoneme', 'heard_phoneme'], name='phoneme_sub_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptphoneme',
            constraint=models.CheckConstraint(condition=models.Q(('verdict__in', ['ok', 'weak', 'substituted', 'deleted', 'uncertain'])), name='attemptphoneme_verdict'),
        ),
        migrations.AddIndex(
            model_name='attemptfeedback',
            index=models.Index(fields=['attempt_word'], name='twisters_at_attempt_001afd_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptfeedback',
            constraint=models.UniqueConstraint(fields=('attempt_word', 'profile'), name='uniq_word_feedback'),
        ),
        migrations.AddIndex(
            model_name='scoringjob',
            index=models.Index(fields=['status', 'created_at'], name='twisters_sc_status_ba8af7_idx'),
        ),
        migrations.AddIndex(
            model_name='scoringjob',
            index=models.Index(fields=['attempt'], name='twisters_sc_attempt_15071c_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoringprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('model_version',), name='uniq_active_profile_per_model'),
        ),
        migrations.AddConstraint(
            model_name='twisterpronunciation',
            constraint=models.UniqueConstraint(fields=('twister', 'word', 'accent'), name='uniq_pronunciation_per_twister'),
        ),
        migrations.AddConstraint(
            model_name='twisterpronunciation',
            constraint=models.UniqueConstraint(condition=models.Q(('twister__isnull', True)), fields=('word', 'accent'), name='uniq_pronunciation_global'),
        ),
        migrations.AddConstraint(
            model_name='userphonemestat',
            constraint=models.UniqueConstraint(fields=('profile', 'phoneme_pair'), name='uniq_phoneme_stat'),
        ),
        migrations.AddIndex(
            model_name='usertwisterstats',
            index=models.Index(fields=['profile', 'mastered_at'], name='twisters_us_profile_e61424_idx'),
        ),
        migrations.AddConstraint(
            model_name='usertwisterstats',
            constraint=models.UniqueConstraint(fields=('profile', 'twister'), name='uniq_user_twister_stats'),
        ),
        migrations.AddIndex(
            model_name='userwordstat',
            index=models.Index(fields=['profile', '-weakness'], name='twisters_us_profile_fb6112_idx'),
        ),
        migrations.AddIndex(
            model_name='userwordstat',
            index=models.Index(fields=['profile', 'next_review_at'], name='twisters_us_profile_fad118_idx'),
        ),
        migrations.AddConstraint(
            model_name='userwordstat',
            constraint=models.UniqueConstraint(fields=('profile', 'word_norm'), name='uniq_word_stat'),
        ),
        migrations.AddConstraint(
            model_name='userwordstat',
            constraint=models.CheckConstraint(condition=models.Q(('weakness__gte', 0), ('weakness__lte', 1)), name='wordstat_weakness_range'),
        ),
    ]
