# Generated by Django 5.2.17 on 2026-09-30 16:02

import django.db.models.deletion
import twisters.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0006_enable_speak_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_band',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('under13', 'Under 13'), ('13plus', '13 or older')], default='unknown', max_length=8),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image'), ('caption', 'Caption')], max_length=8)),
                ('bucket', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=200)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending_upload', 'Pending upload'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending_upload', max_length=14)),
                ('upload_id', models.CharField(blank=True, max_length=120)),
                ('upload_attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='twisters.profile')),
            ],
            bases=(twisters.models.StateMachine, models.Model),
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_recording_id', models.UUIDField(help_text='Client-generated; makes create idempotent')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('layout', models.SlugField(default='camera_text', help_text='Layout id from the web registry; deliberately not an enum so adding one is web-only', max_length=24)),
                ('layout_settings', models.JSONField(blank=True, default=dict)),
                ('crop_rect', models.JSONField(blank=True, null=True)),
                ('trim_start_ms', models.PositiveIntegerField(default=0)),
                ('trim_end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('has_camera', models.BooleanField(default=False)),
                ('has_screen', models.BooleanField(default=False)),
                ('has_mic', models.BooleanField(default=True)),
                ('has_system_audio', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField()),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.BigIntegerField()),
                ('capture_source', models.CharField(choices=[('getUserMedia', 'getUserMedia'), ('getDisplayMedia', 'getDisplayMedia'), ('region_capture', 'Region capture'), ('element_capture', 'Element capture')], default='getUserMedia', max_length=16)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('local_ready', 'Local ready'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='uploading', max_length=12)),
                ('failure_reason', models.CharField(blank=True, max_length=60)),
                ('recovered', models.BooleanField(default=False, help_text='Rebuilt from IndexedDB chunks')),
                ('captions_source', models.CharField(choices=[('none', 'None'), ('alignment', 'Alignment')], default='none', max_length=9)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted')], default='private', max_length=8)),
                ('ended_reason', models.CharField(blank=True, choices=[('user', 'User'), ('limit', 'Limit'), ('device', 'Device'), ('error', 'Error'), ('tab_hidden', 'Tab hidden')], max_length=10)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, help_text='Set by moderation; a hidden take cannot be shared', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording', to='twisters.attempt')),
                ('captions_asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captions_of', to='twisters.mediaasset')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='twisters.profile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='twisters.practicesession')),
                ('thumbnail_asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail_of', to='twisters.mediaasset')),
                ('twister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='twisters.twister')),
                ('video_asset', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_of', to='twisters.mediaasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(twisters.models.StateMachine, models.Model),
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('recording', 'Recording'), ('score_card', 'Score card')], max_length=10)),
                ('target_id', models.UUIDField(help_text='Recording.id, or Attempt.public_id for a score card')),
                ('token_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, help_text='Moderation hold (reports or staff); resolves as 410', null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='twisters.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_ip_hash', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(choices=[('abuse', 'Abusive or harmful'), ('sexual', 'Sexual content'), ('minor', 'Involves a child'), ('privacy', 'Privacy'), ('spam', 'Spam'), ('other', 'Other')], max_length=8)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=9)),
                ('resolved_by', models.CharField(blank=True, help_text='Staff username', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_filed', to='twisters.profile')),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='twisters.sharelink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('recording', 'Recording'), ('voice', 'Voice'), ('thumb', 'Thumbnail'), ('caption', 'Caption')], max_length=9)),
                ('delta_bytes', models.BigIntegerField(help_text='Positive reserves, negative releases')),
                ('reason', models.CharField(choices=[('reserve', 'Reserve'), ('complete', 'Complete'), ('delete', 'Delete'), ('expire', 'Expire'), ('orphan', 'Orphan sweep'), ('reject', 'Rejected upload')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_rows', to='twisters.mediaasset')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_ledger', to='twisters.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('recording_upload', 'Recording upload'), ('voice_storage', 'Voice storage'), ('voice_processing', 'Voice processing'), ('model_improvement', 'Model improvement'), ('terms', 'Terms'), ('marketing', 'Marketing')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='twisters.profile')),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['status', 'created_at'], name='asset_sweep_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('expires_at__isnull', False)), fields=['expires_at'], name='asset_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['profile', 'kind'], name='asset_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(fields=('bucket', 'path'), name='uniq_asset_object'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0), ('size_bytes__lte', 104857600)), name='asset_size_range'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['audio', 'video', 'image', 'caption'])), name='asset_kind'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending_upload', 'uploading', 'uploaded', 'processing', 'ready', 'failed', 'deleted'])), name='asset_status'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['profile', '-created_at'], name='recording_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['expires_at'], name='recording_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(condition=models.Q(('deleted_at__isnull', False)), fields=['deleted_at'], name='recording_purge_idx'),
        ),
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.UniqueConstraint(fields=('profile', 'client_recording_id'), name='uniq_recording_client_id'),
        ),
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.CheckConstraint(condition=models.Q(('trim_end_ms__isnull', True), ('trim_end_ms__gt', models.F('trim_start_ms')), _connector='OR'), name='recording_trim_order'),
        ),
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.CheckConstraint(condition=models.Q(('duration_ms__lte', 600000)), name='recording_duration_max'),
        ),
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0), ('size_bytes__lte', 104857600)), name='recording_size_range'),
        ),
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['private', 'unlisted'])), name='recording_visibility'),
        ),
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['recording', 'local_ready', 'uploading', 'uploaded', 'processing', 'ready', 'failed', 'deleted'])), name='recording_status'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['target_type', 'target_id'], name='twisters_sh_target__1e3386_idx'),
        ),
        migrations.AddConstraint(
            model_name='sharelink',
            constraint=models.UniqueConstraint(fields=('token_hash',), name='uniq_share_token_hash'),
        ),
        migrations.AddConstraint(
            model_name='sharelink',
            constraint=models.CheckConstraint(condition=models.Q(('target_type__in', ['recording', 'score_card'])), name='share_target'),
        ),
        migrations.AddConstraint(
            model_name='moderationreport',
            constraint=models.UniqueConstraint(condition=models.Q(('reporter__isnull', False)), fields=('share_link', 'reporter'), name='uniq_report_user'),
        ),
        migrations.AddConstraint(
            model_name='moderationreport',
            constraint=models.UniqueConstraint(condition=models.Q(('reporter__isnull', True)), fields=('share_link', 'reporter_ip_hash'), name='uniq_report_ip'),
        ),
        migrations.AddConstraint(
            model_name='moderationreport',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['abuse', 'sexual', 'minor', 'privacy', 'spam', 'other'])), name='report_reason'),
        ),
        migrations.AddConstraint(
            model_name='moderationreport',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'actioned', 'dismissed'])), name='report_status'),
        ),
        migrations.AddIndex(
            model_name='storageledger',
            index=models.Index(fields=['profile', 'created_at'], name='twisters_st_profile_d7e40d_idx'),
        ),
        migrations.AddIndex(
            model_name='storageledger',
            index=models.Index(fields=['asset'], name='ledger_asset_idx'),
        ),
        migrations.AddConstraint(
            model_name='storageledger',
            constraint=models.CheckConstraint(condition=models.Q(('delta_bytes', 0), _negated=True), name='ledger_nonzero_delta'),
        ),
        migrations.AddConstraint(
            model_name='storageledger',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['recording', 'voice', 'thumb', 'caption'])), name='ledger_kind'),
        ),
        migrations.AddConstraint(
            model_name='storageledger',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['reserve', 'complete', 'delete', 'expire', 'orphan', 'reject'])), name='ledger_reason'),
        ),
        migrations.AddConstraint(
            model_name='userconsent',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('profile', 'type'), name='uniq_active_consent'),
        ),
        migrations.AddConstraint(
            model_name='userconsent',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['recording_upload', 'voice_storage', 'voice_processing', 'model_improvement', 'terms', 'marketing'])), name='consent_type'),
        ),
    ]
