# Generated by Django 5.2.17 on 2026-09-30 16:51

import django.db.models.deletion
import twisters.models
import twisters.names
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0010_record_flags_and_limits'),
    ]

    operations = [
        # A rename, not remove+add: keeps the flag on takes that were already reminded.
        migrations.RenameField(
            model_name='recording',
            old_name='expiry_reminded_at',
            new_name='reminder_sent_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='public_name',
            field=models.CharField(blank=True, default='', help_text='Opt-in name shown to viewers of recordings the user shares; blank = anonymous', max_length=40, validators=[twisters.names.validate_public_name]),
        ),
        migrations.AddField(
            model_name='recording',
            name='audio_asset',
            field=models.OneToOneField(blank=True, help_text='16 kHz mono WAV made by the worker for later analysis (A2.3)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_audio_of', to='twisters.mediaasset'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the T-3 day expiry e-mail covering this take went out', null=True),
        ),
        migrations.CreateModel(
            name='MediaJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('process', 'Process'), ('analyse', 'Analyse')], max_length=8)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=8)),
                ('tries', models.PositiveSmallIntegerField(default=0)),
                ('max_tries', models.PositiveSmallIntegerField(default=twisters.models.default_job_max_tries)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(help_text='The source video asset the job reads', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='twisters.mediaasset')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='twisters.recording')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(condition=models.Q(('status__in', ['queued', 'running'])), fields=['status', 'created_at'], name='mediajob_active_idx'), models.Index(fields=['recording', 'kind'], name='mediajob_recording_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('recording', 'kind'), name='mediajob_one_active'), models.CheckConstraint(condition=models.Q(('kind__in', ['process', 'analyse'])), name='mediajob_kind'), models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'running', 'done', 'failed'])), name='mediajob_status'), models.CheckConstraint(condition=models.Q(('max_tries__gte', 1), ('tries__lte', models.F('max_tries'))), name='mediajob_tries'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'running'), _negated=True), ('locked_until__isnull', False), _connector='OR'), name='mediajob_running_has_lease')],
            },
            bases=(twisters.models.StateMachine, models.Model),
        ),
    ]
