# Generated by Django 5.2.17 on 2026-09-30 19:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0011_media_jobs_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(help_text='lucide icon name', max_length=40)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=6)),
                ('category', models.CharField(choices=[('start', 'Getting started'), ('streak', 'Streaks'), ('mastery', 'Mastery'), ('skill', 'Skill'), ('explore', 'Explore')], max_length=8)),
                ('criteria', models.JSONField(default=dict)),
                ('xp_reward', models.PositiveSmallIntegerField(default=0)),
                ('verified_only', models.BooleanField(default=False, help_text='Only attempts whose result can be trusted (mastery trust rules) count')),
                ('hidden', models.BooleanField(default=False, help_text='Shown as a secret until unlocked')),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DailyTwister',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('editorial', 'Editorial'), ('auto', 'Automatic')], default='editorial', max_length=9)),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday, UTC')),
                ('best_score', models.PositiveSmallIntegerField()),
                ('achieved_at', models.DateTimeField()),
                ('rank', models.PositiveIntegerField()),
                ('built_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'leaderboard entries',
                'ordering': ['week_start', 'twister', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress', models.FloatField(blank=True, help_text='0..1 at unlock; NULL for event rules', null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False, help_text='The user has been shown the toast')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_from_boards',
            field=models.BooleanField(default=False, help_text='Opt out of every public leaderboard (D18)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_freezes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Banked streak freezes; one bridges one missed day (D16)'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('streak_freezes__gte', 0), ('streak_freezes__lte', 2)), name='profile_streak_freezes_range'),
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.CheckConstraint(condition=models.Q(('tier__in', ['bronze', 'silver', 'gold'])), name='achievement_tier'),
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['start', 'streak', 'mastery', 'skill', 'explore'])), name='achievement_category'),
        ),
        migrations.AddField(
            model_name='dailytwister',
            name='twister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_features', to='twisters.twister'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='best_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_entries', to='twisters.attempt'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_entries', to='twisters.profile'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='twister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_entries', to='twisters.twister'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(db_column='achievement_code', on_delete=django.db.models.deletion.PROTECT, related_name='unlocks', to='twisters.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='twisters.profile'),
        ),
        migrations.AddConstraint(
            model_name='dailytwister',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['editorial', 'auto'])), name='daily_twister_source'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['week_start', 'twister', 'rank'], name='leaderboard_rank_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(fields=('week_start', 'twister', 'profile'), name='uniq_leaderboard_entry'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.CheckConstraint(condition=models.Q(('best_score__gte', 0), ('best_score__lte', 100)), name='leaderboard_score_range'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='leaderboard_rank_positive'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['profile', 'seen'], name='user_achievement_seen_idx'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('profile', 'achievement'), name='uniq_user_achievement'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.CheckConstraint(condition=models.Q(('progress__isnull', True), models.Q(('progress__gte', 0), ('progress__lte', 1)), _connector='OR'), name='user_achievement_progress_range'),
        ),
    ]
