"""Seed the 06d achievement catalogue and its two feature flags (spec 14 S2).

Data only; the schema is `0012` (PostgreSQL cannot ALTER a table after inserting rows that reference
it in the same transaction, the same reason as 0007/0008). The catalogue below is a *frozen copy* of
`twisters/progress/catalogue.py` as of this commit: migrations must not import live code or settings.
Later catalogue edits reach the database through `manage.py sync_achievements`.

Reverse removes only what this migration seeded, including any unlocks of those badges (the schema
reverse would drop them anyway).
"""

from django.db import migrations

ACHIEVEMENTS = [{'code': 'first_word',
  'name': 'First Words',
  'description': 'Finish your first attempt.',
  'icon': 'mic',
  'tier': 'bronze',
  'category': 'start',
  'criteria': {'type': 'attempts', 'min': 1},
  'xp_reward': 10,
  'verified_only': False,
  'hidden': False,
  'sort_order': 10},
 {'code': 'first_test',
  'name': 'Put to the Test',
  'description': 'Finish your first scored Test.',
  'icon': 'target',
  'tier': 'bronze',
  'category': 'start',
  'criteria': {'type': 'test_attempts', 'min': 1},
  'xp_reward': 10,
  'verified_only': False,
  'hidden': False,
  'sort_order': 20},
 {'code': 'streak_3',
  'name': 'Warming Up',
  'description': 'Practise 3 days in a row.',
  'icon': 'flame',
  'tier': 'bronze',
  'category': 'streak',
  'criteria': {'type': 'streak', 'min': 3},
  'xp_reward': 15,
  'verified_only': False,
  'hidden': False,
  'sort_order': 30},
 {'code': 'streak_7',
  'name': 'On Fire',
  'description': 'Practise 7 days in a row.',
  'icon': 'flame',
  'tier': 'silver',
  'category': 'streak',
  'criteria': {'type': 'streak', 'min': 7},
  'xp_reward': 30,
  'verified_only': False,
  'hidden': False,
  'sort_order': 40},
 {'code': 'streak_14',
  'name': 'Two Weeks',
  'description': 'Practise 14 days in a row.',
  'icon': 'flame',
  'tier': 'silver',
  'category': 'streak',
  'criteria': {'type': 'streak', 'min': 14},
  'xp_reward': 50,
  'verified_only': False,
  'hidden': False,
  'sort_order': 50},
 {'code': 'streak_30',
  'name': 'Unstoppable',
  'description': 'Practise 30 days in a row.',
  'icon': 'flame',
  'tier': 'gold',
  'category': 'streak',
  'criteria': {'type': 'streak', 'min': 30},
  'xp_reward': 100,
  'verified_only': False,
  'hidden': False,
  'sort_order': 60},
 {'code': 'mastered_1',
  'name': 'Tongue Tied No More',
  'description': 'Master 1 twister.',
  'icon': 'trophy',
  'tier': 'bronze',
  'category': 'mastery',
  'criteria': {'type': 'mastered', 'min': 1},
  'xp_reward': 25,
  'verified_only': False,
  'hidden': False,
  'sort_order': 70},
 {'code': 'mastered_10',
  'name': 'Word Smith',
  'description': 'Master 10 twisters.',
  'icon': 'trophy',
  'tier': 'silver',
  'category': 'mastery',
  'criteria': {'type': 'mastered', 'min': 10},
  'xp_reward': 60,
  'verified_only': False,
  'hidden': False,
  'sort_order': 80},
 {'code': 'mastered_50',
  'name': 'Twister Pro',
  'description': 'Master 50 twisters.',
  'icon': 'trophy',
  'tier': 'gold',
  'category': 'mastery',
  'criteria': {'type': 'mastered', 'min': 50},
  'xp_reward': 150,
  'verified_only': False,
  'hidden': False,
  'sort_order': 90},
 {'code': 'mastered_100',
  'name': 'Legend',
  'description': 'Master 100 twisters.',
  'icon': 'trophy',
  'tier': 'gold',
  'category': 'mastery',
  'criteria': {'type': 'mastered', 'min': 100},
  'xp_reward': 300,
  'verified_only': False,
  'hidden': False,
  'sort_order': 100},
 {'code': 'perfect_100',
  'name': 'Flawless',
  'description': 'Score 100 on a twister of 10 words or more.',
  'icon': 'sparkles',
  'tier': 'gold',
  'category': 'skill',
  'criteria': {'type': 'attempt_score', 'min': 100, 'min_words': 10, 'kinds': ['test', 'record']},
  'xp_reward': 50,
  'verified_only': True,
  'hidden': False,
  'sort_order': 110},
 {'code': 'insane_clear',
  'name': 'Insane in the Membrane',
  'description': 'Score 80 or more on an Insane twister.',
  'icon': 'skull',
  'tier': 'gold',
  'category': 'skill',
  'criteria': {'type': 'attempt_score', 'min': 80, 'difficulty': 4, 'kinds': ['test', 'record']},
  'xp_reward': 50,
  'verified_only': True,
  'hidden': False,
  'sort_order': 120},
 {'code': 'marathoner',
  'name': 'Marathoner',
  'description': 'Score 80 or more on a twister of 100 words or more.',
  'icon': 'route',
  'tier': 'silver',
  'category': 'skill',
  'criteria': {'type': 'attempt_score', 'min': 80, 'min_words': 100, 'kinds': ['test', 'record']},
  'xp_reward': 40,
  'verified_only': True,
  'hidden': False,
  'sort_order': 130},
 {'code': 'speed_demon',
  'name': 'Speed Demon',
  'description': 'Reach 180 words per minute with 90% accuracy.',
  'icon': 'zap',
  'tier': 'silver',
  'category': 'skill',
  'criteria': {'type': 'attempt_wpm', 'min': 180, 'min_accuracy': 0.9, 'kinds': ['test', 'record']},
  'xp_reward': 40,
  'verified_only': True,
  'hidden': False,
  'sort_order': 140},
 {'code': 'sweep_hissers',
  'name': 'Hisser Master',
  'description': 'Master 5 twisters in one sound family.',
  'icon': 'medal',
  'tier': 'silver',
  'category': 'mastery',
  'criteria': {'type': 'category_mastered', 'category': 'hissers', 'min': 5},
  'xp_reward': 50,
  'verified_only': False,
  'hidden': False,
  'sort_order': 150},
 {'code': 'sweep_poppers',
  'name': 'Popper Master',
  'description': 'Master 5 twisters in one sound family.',
  'icon': 'medal',
  'tier': 'silver',
  'category': 'mastery',
  'criteria': {'type': 'category_mastered', 'category': 'poppers', 'min': 5},
  'xp_reward': 50,
  'verified_only': False,
  'hidden': False,
  'sort_order': 160},
 {'code': 'sweep_rollers',
  'name': 'Roller Master',
  'description': 'Master 5 twisters in one sound family.',
  'icon': 'medal',
  'tier': 'silver',
  'category': 'mastery',
  'criteria': {'type': 'category_mastered', 'category': 'rollers', 'min': 5},
  'xp_reward': 50,
  'verified_only': False,
  'hidden': False,
  'sort_order': 170},
 {'code': 'sweep_th',
  'name': 'TH Master',
  'description': 'Master 5 twisters in one sound family.',
  'icon': 'medal',
  'tier': 'silver',
  'category': 'mastery',
  'criteria': {'type': 'category_mastered', 'category': 'th-tangles', 'min': 5},
  'xp_reward': 50,
  'verified_only': False,
  'hidden': False,
  'sort_order': 180},
 {'code': 'sweep_vowels',
  'name': 'Vowel Master',
  'description': 'Master 5 twisters in one sound family.',
  'icon': 'medal',
  'tier': 'silver',
  'category': 'mastery',
  'criteria': {'type': 'category_mastered', 'category': 'vowel-vortex', 'min': 5},
  'xp_reward': 50,
  'verified_only': False,
  'hidden': False,
  'sort_order': 190},
 {'code': 'sweep_benders',
  'name': 'Bender Master',
  'description': 'Master 5 twisters in one sound family.',
  'icon': 'medal',
  'tier': 'silver',
  'category': 'mastery',
  'criteria': {'type': 'category_mastered', 'category': 'brain-benders', 'min': 5},
  'xp_reward': 50,
  'verified_only': False,
  'hidden': False,
  'sort_order': 200},
 {'code': 'all_levels',
  'name': 'Ladder Climber',
  'description': 'Pass a Test with 80 or more at every level.',
  'icon': 'mountain',
  'tier': 'silver',
  'category': 'skill',
  'criteria': {'type': 'levels_passed', 'min_score': 80, 'difficulties': [1, 2, 3, 4]},
  'xp_reward': 40,
  'verified_only': True,
  'hidden': False,
  'sort_order': 210},
 {'code': 'read_10min',
  'name': 'Steady Pacer',
  'description': 'Read along for 10 minutes in total.',
  'icon': 'timer',
  'tier': 'bronze',
  'category': 'start',
  'criteria': {'type': 'read_along_ms', 'min': 600000},
  'xp_reward': 20,
  'verified_only': False,
  'hidden': False,
  'sort_order': 220},
 {'code': 'recorded_1',
  'name': 'On Camera',
  'description': 'Save your first recording.',
  'icon': 'video',
  'tier': 'bronze',
  'category': 'start',
  'criteria': {'type': 'recordings_saved', 'min': 1},
  'xp_reward': 20,
  'verified_only': False,
  'hidden': False,
  'sort_order': 230},
 {'code': 'comeback',
  'name': 'Comeback Kid',
  'description': "Raise a twister's best score by 25 points or more.",
  'icon': 'trending-up',
  'tier': 'silver',
  'category': 'skill',
  'criteria': {'type': 'score_gain', 'min': 25, 'kinds': ['test']},
  'xp_reward': 30,
  'verified_only': True,
  'hidden': False,
  'sort_order': 240},
 {'code': 'explorer',
  'name': 'Explorer',
  'description': 'Try a twister from every category.',
  'icon': 'compass',
  'tier': 'silver',
  'category': 'explore',
  'criteria': {'type': 'categories_attempted'},
  'xp_reward': 30,
  'verified_only': False,
  'hidden': False,
  'sort_order': 250}]

# `weekly_boards` ships off: it needs the hourly `build_leaderboard` job scheduled first.
FLAGS = {
    "achievements": (True, "Badges, XP rewards and unlock toasts"),
    "weekly_boards": (False, "Weekly leaderboard on the daily twister"),
}


def forwards(apps, schema_editor):
    Achievement = apps.get_model("twisters", "Achievement")
    for row in ACHIEVEMENTS:
        code = row["code"]
        Achievement.objects.update_or_create(
            code=code, defaults={**{k: v for k, v in row.items() if k != "code"}, "active": True}
        )
    FeatureFlag = apps.get_model("twisters", "FeatureFlag")
    for code, (enabled, description) in FLAGS.items():
        FeatureFlag.objects.update_or_create(
            code=code, defaults={"enabled": enabled, "description": description}
        )


def backwards(apps, schema_editor):
    codes = [row["code"] for row in ACHIEVEMENTS]
    apps.get_model("twisters", "UserAchievement").objects.filter(achievement_id__in=codes).delete()
    apps.get_model("twisters", "Achievement").objects.filter(code__in=codes).delete()
    apps.get_model("twisters", "FeatureFlag").objects.filter(code__in=list(FLAGS)).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("twisters", "0012_progress_schema"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
