# Generated by Django 5.2.17 on 2026-10-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0013_progress_seeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='Account is pending deletion from this moment (D21)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletion_scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Purged by `purge_deleted_accounts` once this has passed', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='night_owl',
            field=models.BooleanField(default=False, help_text='Streak day starts at NIGHT_OWL_CUTOFF_HOUR local time instead of midnight (D23)'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deletion_requested_at__isnull', True), ('deletion_scheduled_for__isnull', True)), models.Q(('deletion_requested_at__isnull', False), ('deletion_scheduled_for__gte', models.F('deletion_requested_at')), ('deletion_scheduled_for__isnull', False)), _connector='OR'), name='profile_deletion_window'),
        ),
    ]
