# Generated by Django 5.2.17 on 2026-10-01 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0015_round1_seeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='twister',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Set exactly when the twister is private', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_twisters', to='twisters.profile'),
        ),
        migrations.AddField(
            model_name='twister',
            name='topic',
            field=models.CharField(blank=True, help_text='What the owner asked for (generated twisters only)', max_length=120),
        ),
        migrations.AddField(
            model_name='twister',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='public', help_text='`private` = generated for one person (D25); never listed for anyone else', max_length=7),
        ),
        migrations.AddConstraint(
            model_name='twister',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', True), ('visibility', 'public')), models.Q(('is_published', False), ('owner__isnull', False), ('visibility', 'private')), _connector='OR'), name='twister_visibility_owner'),
        ),
        migrations.AddField(
            model_name='generationusage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_usage', to='twisters.profile'),
        ),
        migrations.AddConstraint(
            model_name='generationusage',
            constraint=models.UniqueConstraint(fields=('profile', 'day'), name='generation_usage_profile_day'),
        ),
    ]
