# Generated by Django 5.2.17 on 2026-10-01 01:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0016_round2_generate_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderPreference',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reminder_preference', serialize=False, to='twisters.profile')),
                ('enabled', models.BooleanField(default=False)),
                ('hour_local', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('last_sent_on', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('hour_local__gte', 0), ('hour_local__lte', 23)), name='reminder_hour_local_range')],
            },
        ),
    ]
