# Generated by Django 5.2.17 on 2026-10-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0019_word_stat_mastered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='spot_check_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the server asked the client for the audio (docs/features/13 §3.3)', null=True),
        ),
        migrations.AddField(
            model_name='scoringjob',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Lease; a running job past it is re-queued', null=True),
        ),
        migrations.AddField(
            model_name='scoringjob',
            name='max_tries',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='scoringjob',
            name='result',
            field=models.JSONField(blank=True, default=dict, help_text='Worker summary: no audio, no transcript'),
        ),
        migrations.AddField(
            model_name='scoringjob',
            name='worker_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='spot_check_delta',
            field=models.FloatField(blank=True, help_text='Signed: device score minus worker score (positive = generous)', null=True),
        ),
        migrations.AddConstraint(
            model_name='scoringjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('attempt', 'kind'), name='uniq_active_scoring_job'),
        ),
        migrations.AddConstraint(
            model_name='scoringjob',
            constraint=models.CheckConstraint(condition=models.Q(('tries__lte', models.F('max_tries'))), name='scoring_job_tries_le_max'),
        ),
    ]
