# Generated by Django 5.2.17 on 2026-10-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twisters", "0021_calibrate_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringjob",
            name="recording",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for kind=record: the recording whose analysis audio is scored",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_jobs",
                to="twisters.recording",
            ),
        ),
        migrations.AlterField(
            model_name="scoringjob",
            name="attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoring_jobs",
                to="twisters.attempt",
            ),
        ),
        migrations.AlterField(
            model_name="scoringjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("spot_check", "Spot check"),
                    ("verify", "Verify"),
                    ("device_unsupported", "Device unsupported"),
                    ("record", "Record"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="scoringjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "running"])),
                fields=("recording", "kind"),
                name="uniq_active_record_scoring_job",
            ),
        ),
        migrations.AddConstraint(
            model_name="scoringjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("attempt__isnull", False),
                        ("kind__in", ["spot_check", "verify", "device_unsupported"]),
                        ("recording__isnull", True),
                    ),
                    models.Q(
                        ("attempt__isnull", True),
                        ("kind", "record"),
                        ("recording__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="scoring_job_one_subject",
            ),
        ),
    ]
