# Generated by Django 5.2.17 on 2026-10-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twisters", "0022_record_scoring_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "limit",
                    models.CharField(
                        help_text="recordings, recording_ms or storage_bytes",
                        max_length=20,
                    ),
                ),
                ("plan_code", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota_hits",
                        to="twisters.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="twisters_qu_created_1bbd57_idx"
                    ),
                    models.Index(
                        fields=["profile", "limit", "-created_at"],
                        name="quotahit_dedupe_idx",
                    ),
                ],
            },
        ),
    ]
