# Generated by Django 5.2.17 on 2026-10-03 03:01

import twisters.avatars
import twisters.names
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0023_quota_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_source',
            field=models.CharField(choices=[('photo', 'Sign-in photo'), ('emoji', 'Emoji')], default='photo', help_text='Which avatar the person shows: their sign-in photo (when they have one) or the emoji', max_length=5),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='confetti',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(blank=True, choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark'), ('reading', 'Reading')], default='', help_text='Blank = never chosen on any device: the first device that signs in seeds it', max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_emoji',
            field=models.CharField(default='🗣️', max_length=8, validators=[twisters.avatars.validate_avatar_emoji]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Starts as the sign-in name; the person can change it. Shown to them only', max_length=40, validators=[twisters.names.validate_display_name]),
        ),
    ]
