# Generated by Django 5.2.17 on 2026-10-03 03:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0024_profile_avatar_source_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('level_up', 'Level up'), ('achievement', 'Achievement'), ('streak_milestone', 'Streak milestone'), ('twister_mastered', 'Twister mastered'), ('personal_best', 'Personal best')], max_length=20)),
                ('ref', models.CharField(help_text="Natural key, e.g. 'level:5' or 'ach:first-steps'", max_length=80)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='userpreference',
            name='daily_goal_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Attempts to aim for each local day; 0 = no goal', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddConstraint(
            model_name='userpreference',
            constraint=models.CheckConstraint(condition=models.Q(('daily_goal_attempts__gte', 0), ('daily_goal_attempts__lte', 50)), name='pref_daily_goal_attempts_range'),
        ),
        migrations.AddField(
            model_name='profileevent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='twisters.profile'),
        ),
        migrations.AddIndex(
            model_name='profileevent',
            index=models.Index(fields=['profile', '-created_at'], name='profile_event_recent'),
        ),
        migrations.AddConstraint(
            model_name='profileevent',
            constraint=models.UniqueConstraint(fields=('profile', 'ref'), name='uniq_profile_event_ref'),
        ),
    ]
