# Generated by Django 5.2.17 on 2026-10-03 09:41

from django.db import migrations, models


def backfill_canonical_email(apps, schema_editor):
    """Existing accounts get their canonical inbox so a new alias of one of them is caught too. The helper is
    imported here (not copied) because it is pure; if its rules change later, re-run this as a new migration."""
    from twisters.emailpolicy import canonical_email

    Profile = apps.get_model("twisters", "Profile")
    batch = []
    for profile in Profile.objects.exclude(email="").only("id", "email").iterator(chunk_size=500):
        profile.canonical_email = canonical_email(profile.email)
        batch.append(profile)
        if len(batch) >= 500:
            Profile.objects.bulk_update(batch, ["canonical_email"])
            batch = []
    if batch:
        Profile.objects.bulk_update(batch, ["canonical_email"])


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0025_profile_events_daily_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='canonical_email',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='The inbox this address reaches (Gmail dots and +tags folded): one account per inbox', max_length=254),
        ),
        migrations.RunPython(backfill_canonical_email, migrations.RunPython.noop),
    ]
