# Generated by Django 5.2.17 on 2026-10-04 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisters', '0026_profile_canonical_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicStatSnapshot',
            fields=[
                ('key', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('value', models.BigIntegerField(default=0)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SignupAttribution',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attribution', serialize=False, to='twisters.profile')),
                ('intent', models.CharField(choices=[('practise', 'Practise'), ('save_demo', 'Save demo score'), ('favourite', 'Favourite'), ('generate', 'Generate'), ('record', 'Record'), ('locked_filter', 'Locked filter'), ('locked_nav', 'Locked page'), ('hero_cta', 'Hero button'), ('header_cta', 'Header button'), ('footer_cta', 'Footer button'), ('direct', 'Direct')], default='direct', max_length=16)),
                ('first_path', models.CharField(blank=True, max_length=120)),
                ('utm_source', models.CharField(blank=True, max_length=40)),
                ('utm_medium', models.CharField(blank=True, max_length=40)),
                ('utm_campaign', models.CharField(blank=True, max_length=40)),
                ('demo_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='twister',
            name='teaser_position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1..12: shown to signed-out visitors, in this order (public site, D44). Blank = members only', null=True),
        ),
        migrations.AlterField(
            model_name='syncbatch',
            name='kind',
            field=models.CharField(choices=[('guest_signup', 'Guest sign-up'), ('offline_queue', 'Offline queue'), ('demo_claim', 'Demo score claimed after sign-up')], default='guest_signup', max_length=14),
        ),
        migrations.AddConstraint(
            model_name='syncbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'demo_claim')), fields=('profile',), name='uniq_demo_claim_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='twister',
            constraint=models.UniqueConstraint(condition=models.Q(('teaser_position__isnull', False)), fields=('teaser_position',), name='twister_teaser_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='twister',
            constraint=models.CheckConstraint(condition=models.Q(('teaser_position__isnull', True), models.Q(('owner__isnull', True), ('teaser_position__gte', 1), ('visibility', 'public')), _connector='OR'), name='twister_teaser_public_only'),
        ),
    ]
