/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as TwistersIndexRouteImport } from './routes/twisters.index'
import { Route as TwistersSlugRouteImport } from './routes/twisters.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TwistersIndexRoute = TwistersIndexRouteImport.update({
  id: '/twisters/',
  path: '/twisters/',
  getParentRoute: () => rootRouteImport,
} as any)
const TwistersSlugRoute = TwistersSlugRouteImport.update({
  id: '/twisters/$slug',
  path: '/twisters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/twisters/$slug': typeof TwistersSlugRoute
  '/twisters/': typeof TwistersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/twisters/$slug': typeof TwistersSlugRoute
  '/twisters': typeof TwistersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/twisters/$slug': typeof TwistersSlugRoute
  '/twisters/': typeof TwistersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/practice'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/twisters/$slug'
    | '/twisters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/practice'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/twisters/$slug'
    | '/twisters'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/practice'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/twisters/$slug'
    | '/twisters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PracticeRoute: typeof PracticeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  TwistersSlugRoute: typeof TwistersSlugRoute
  TwistersIndexRoute: typeof TwistersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twisters/': {
      id: '/twisters/'
      path: '/twisters'
      fullPath: '/twisters/'
      preLoaderRoute: typeof TwistersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twisters/$slug': {
      id: '/twisters/$slug'
      path: '/twisters/$slug'
      fullPath: '/twisters/$slug'
      preLoaderRoute: typeof TwistersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PracticeRoute: PracticeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  TwistersSlugRoute: TwistersSlugRoute,
  TwistersIndexRoute: TwistersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
