/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyTwistersRouteImport } from './routes/my-twisters'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DevCalibrateRouteImport } from './routes/dev.calibrate'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as TwistersIndexRouteImport } from './routes/twisters.index'
import { Route as TwistersSlugRouteImport } from './routes/twisters.$slug'
import { Route as UnsubscribeTokenRouteImport } from './routes/unsubscribe.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTwistersRoute = MyTwistersRouteImport.update({
  id: '/my-twisters',
  path: '/my-twisters',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DevCalibrateRoute = DevCalibrateRouteImport.update({
  id: '/dev/calibrate',
  path: '/dev/calibrate',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TwistersIndexRoute = TwistersIndexRouteImport.update({
  id: '/twisters/',
  path: '/twisters/',
  getParentRoute: () => rootRouteImport,
} as any)
const TwistersSlugRoute = TwistersSlugRouteImport.update({
  id: '/twisters/$slug',
  path: '/twisters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeTokenRoute = UnsubscribeTokenRouteImport.update({
  id: '/unsubscribe/$token',
  path: '/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/favorites': typeof FavoritesRoute
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/my-twisters': typeof MyTwistersRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recordings': typeof RecordingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/calibrate': typeof DevCalibrateRoute
  '/r/$token': typeof RTokenRoute
  '/s/$token': typeof STokenRoute
  '/twisters/$slug': typeof TwistersSlugRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/twisters/': typeof TwistersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/favorites': typeof FavoritesRoute
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/my-twisters': typeof MyTwistersRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recordings': typeof RecordingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/calibrate': typeof DevCalibrateRoute
  '/r/$token': typeof RTokenRoute
  '/s/$token': typeof STokenRoute
  '/twisters/$slug': typeof TwistersSlugRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/twisters': typeof TwistersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/favorites': typeof FavoritesRoute
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/my-twisters': typeof MyTwistersRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recordings': typeof RecordingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/calibrate': typeof DevCalibrateRoute
  '/r/$token': typeof RTokenRoute
  '/s/$token': typeof STokenRoute
  '/twisters/$slug': typeof TwistersSlugRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/twisters/': typeof TwistersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/favorites'
    | '/generate'
    | '/login'
    | '/my-twisters'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/recordings'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/auth/callback'
    | '/dev/calibrate'
    | '/r/$token'
    | '/s/$token'
    | '/twisters/$slug'
    | '/unsubscribe/$token'
    | '/twisters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/favorites'
    | '/generate'
    | '/login'
    | '/my-twisters'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/recordings'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/auth/callback'
    | '/dev/calibrate'
    | '/r/$token'
    | '/s/$token'
    | '/twisters/$slug'
    | '/unsubscribe/$token'
    | '/twisters'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/favorites'
    | '/generate'
    | '/login'
    | '/my-twisters'
    | '/practice'
    | '/privacy'
    | '/profile'
    | '/recordings'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/auth/callback'
    | '/dev/calibrate'
    | '/r/$token'
    | '/s/$token'
    | '/twisters/$slug'
    | '/unsubscribe/$token'
    | '/twisters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  FavoritesRoute: typeof FavoritesRoute
  GenerateRoute: typeof GenerateRoute
  LoginRoute: typeof LoginRoute
  MyTwistersRoute: typeof MyTwistersRoute
  PracticeRoute: typeof PracticeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RecordingsRoute: typeof RecordingsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DevCalibrateRoute: typeof DevCalibrateRoute
  RTokenRoute: typeof RTokenRoute
  STokenRoute: typeof STokenRoute
  TwistersSlugRoute: typeof TwistersSlugRoute
  UnsubscribeTokenRoute: typeof UnsubscribeTokenRoute
  TwistersIndexRoute: typeof TwistersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-twisters': {
      id: '/my-twisters'
      path: '/my-twisters'
      fullPath: '/my-twisters'
      preLoaderRoute: typeof MyTwistersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/calibrate': {
      id: '/dev/calibrate'
      path: '/dev/calibrate'
      fullPath: '/dev/calibrate'
      preLoaderRoute: typeof DevCalibrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twisters/': {
      id: '/twisters/'
      path: '/twisters'
      fullPath: '/twisters/'
      preLoaderRoute: typeof TwistersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twisters/$slug': {
      id: '/twisters/$slug'
      path: '/twisters/$slug'
      fullPath: '/twisters/$slug'
      preLoaderRoute: typeof TwistersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$token': {
      id: '/unsubscribe/$token'
      path: '/unsubscribe/$token'
      fullPath: '/unsubscribe/$token'
      preLoaderRoute: typeof UnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  FavoritesRoute: FavoritesRoute,
  GenerateRoute: GenerateRoute,
  LoginRoute: LoginRoute,
  MyTwistersRoute: MyTwistersRoute,
  PracticeRoute: PracticeRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RecordingsRoute: RecordingsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DevCalibrateRoute: DevCalibrateRoute,
  RTokenRoute: RTokenRoute,
  STokenRoute: STokenRoute,
  TwistersSlugRoute: TwistersSlugRoute,
  UnsubscribeTokenRoute: UnsubscribeTokenRoute,
  TwistersIndexRoute: TwistersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
